name: finantrack

networks:
  finantrack-network:
    driver: bridge

services:
  finances-manager:
    image: finances-manager:local
    entrypoint:
      ['air', '-c', '/app/deployments/docker/finances-manager/.air.toml']
    build:
      context: ../../
      dockerfile: ./deployments/docker/finances-manager/debug.go.Dockerfile
    ports:
      # http rest api
      - '6000:6000'
    environment:
      - FINANCES_MANAGER_HTTP_SERVER_PORT=6000
      - FINANCES_MANAGER_DB_HOST=${FINANCES_MANAGER_DB_HOST}
      - FINANCES_MANAGER_DB_PORT=${FINANCES_MANAGER_DB_PORT}
      - FINANCES_MANAGER_DB_USER=${FINANCES_MANAGER_DB_USER}
      - FINANCES_MANAGER_DB_PASS=${FINANCES_MANAGER_DB_PASS}
      - FINANCES_MANAGER_DB_NAME=${FINANCES_MANAGER_DB_NAME}
      - FINANCES_MANAGER_DB_ENGINE=${FINANCES_MANAGER_DB_ENGINE}
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4317
    working_dir: /app
    volumes:
      - ../..:/app
    networks:
      - finantrack-network

  web:
    image: web:local
    entrypoint: ['air', '-c', '/app/deployments/docker/web/.air.toml']
    build:
      context: ../../
      dockerfile: ./deployments/docker/web/debug.go.Dockerfile
    ports:
      # http rest api
      - '8000:8000'
    environment:
      - WEB_HTTP_SERVER_PORT=8000
    volumes:
      - ../..:/app
    networks:
      - finantrack-network
    profiles:
      - web

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - '16686:16686' # Jaeger UI
      - '14250:14250' # For OpenTelemetry gRPC traces
      - '14268:14268' # For OpenTelemetry HTTP traces
      - '4317' # For gRPC traces
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411 # Optional: Zipkin-compatible endpoint
    networks:
      - finantrack-network
